### ISSUE TITLE
Identificare una icona per i contatti

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/bastione-infetti#30]
Va inserita nella barra menù, deve essere rilasciata con licenza che ne permetta il riutilizzo (apache licence o creative commons o similari). Alcune sono qui https://commons.wikimedia.org/wiki/Category:Mail

Deve essere in formato vettoriale, svg o al limite png

**Comment by Emmecci** [comment]
aranciorosso: https://www.google.it/search?q=goo&biw=1226&bih=621&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_qJuv1fvOAhWJnRoKHV28BEYQ_AUIBygC#q=icons+contact&tbs=ic:specific,isc:orange,sur:f&tbm=isch&imgrc=SIJdSx1qjQ2ErM%3A

https://commons.wikimedia.org/wiki/File:Circle-icons-contacts.svg?uselang=it

https://commons.wikimedia.org/wiki/File:Icons8_flat_contacts.svg?uselang=it

bianconerogrigio: https://www.google.it/search?q=goo&biw=1226&bih=621&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_qJuv1fvOAhWJnRoKHV28BEYQ_AUIBygC#tbm=isch&tbs=rimg%3ACUiCXUsdao0NIjimtsdTlPx0o1r0fxrp-voDw2wlmA65sklU3cZgSHcWLnAaId97F8Pe6D62kSoWHRVEqeLDMIMnGyoSCaa2x1OU_1HSjEa77zJY_1WlmrKhIJWvR_1Gun6-gMRaQMz7SD3H5gqEgnDbCWYDrmySRFlSY1338ZYLyoSCVTdxmBIdxYuEdM7WMXOW1qRKhIJcBoh33sXw94RSs1wyVT5pvgqEgnoPraRKhYdFRG7ANFdRVwkXCoSCUSp4sMwgycbEfHQ_18UwF-2g&q=icons%20contact&imgrc=gUhgQFPFF5OkXM%3A

https://www.google.it/search?q=goo&biw=1226&bih=621&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_qJuv1fvOAhWJnRoKHV28BEYQ_AUIBygC#q=icons+contact&tbs=isc:orange,sur:f,ic:gray&tbm=isch&imgrc=tIUxZqG3HZE4xM%3A

https://www.google.it/search?q=goo&biw=1226&bih=621&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_qJuv1fvOAhWJnRoKHV28BEYQ_AUIBygC#tbm=isch&tbs=rimg%3ACbSFMWahtx2RIjgNr9kUoEzuJmw12yY5hn8hFiUQ91Xpt9RU4W2caDV_1q9Rggby4KG23oI1MLEweAfRlEi672CMvoioSCQ2v2RSgTO4mEXCM051J9TdSKhIJbDXbJjmGfyERWBXmQDLhLisqEgkWJRD3Vem31BFHp8-6euRilioSCVThbZxoNX-rEX-tudOEtELOKhIJ1GCBvLgobbcRHJfWKWTl6UIqEgmgjUwsTB4B9BG8cv8TBeZAGioSCWUSLrvYIy-iEUR7uep1-DkH&q=icons%20contact&imgrc=mUXa-y6kUHc8bM%3A

https://www.google.it/search?q=goo&biw=1226&bih=621&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_qJuv1fvOAhWJnRoKHV28BEYQ_AUIBygC#tbm=isch&tbs=rimg%3ACbSFMWahtx2RIjgNr9kUoEzuJmw12yY5hn8hFiUQ91Xpt9RU4W2caDV_1q9Rggby4KG23oI1MLEweAfRlEi672CMvoioSCQ2v2RSgTO4mEXCM051J9TdSKhIJbDXbJjmGfyERWBXmQDLhLisqEgkWJRD3Vem31BFHp8-6euRilioSCVThbZxoNX-rEX-tudOEtELOKhIJ1GCBvLgobbcRHJfWKWTl6UIqEgmgjUwsTB4B9BG8cv8TBeZAGioSCWUSLrvYIy-iEUR7uep1-DkH&q=icons%20contact&imgrc=M_pWDbAfV7GDWM%3A

https://www.google.it/search?q=goo&biw=1226&bih=621&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_qJuv1fvOAhWJnRoKHV28BEYQ_AUIBygC#tbm=isch&tbs=rimg%3ACTP6Vg2wH1exIjjiy6li72M9T0jAIPHhEpu9axmqfyttzMzgLh9jM7qQrcH2amFaMsOULkJiA6jN6vEFSQtLX13v3yoSCeLLqWLvYz1PEciEEz1KXxOFKhIJSMAg8eESm70RkwRXz-RnfMwqEglrGap_1K23MzBHMR-gRVMI16CoSCeAuH2MzupCtEU9K4S8BKWuwKhIJwfZqYVoyw5QRJCGogsr8k58qEgkuQmIDqM3q8RH-RAbtLlHyxCoSCQVJC0tfXe_1fESmPdexgtSUe&q=icons%20contact&imgrc=OYu7IlyvSuOV5M%3A

**Comment by Emmecci** [comment]
bianconero: https://www.google.it/search?q=goo&biw=1226&bih=621&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_qJuv1fvOAhWJnRoKHV28BEYQ_AUIBygC#tbm=isch&tbs=rimg%3ACYFIYEBTxReTIjjQ3Zlz-lViS1MomAuKx5WPaoh3gMYtVeDfAYDdnkkd5bQ3rQdCW813pnS2Kw8XHI30S4hc2eixDCoSCdDdmXP6VWJLEUwiAdAdZ_1IgKhIJUyiYC4rHlY8Rg3X0c1rLY7MqEglqiHeAxi1V4BFsQqa_1K_1K7qCoSCd8BgN2eSR3lER4nw_1gV6bBFKhIJtDetB0JbzXcR6k26Kobbz0wqEgmmdLYrDxccjREVCYZppfhONSoSCfRLiFzZ6LEMEVk1Aq3vFuPV&q=icons%20contact&imgrc=tDetB0JbzXeXHM%3A

**Comment by cristianolongo** [comment]
Accollata https://commons.wikimedia.org/wiki/File:Ic_quick_contacts_dialer_48px.svg

**Comment by cristianolongo** [comment]
ae2fc63e35b61fa6835c0755399b7f7afea9ed1e
