### ISSUE TITLE
Dopo che viene inserito l'ultimo evento in home page, la mappa "sbrafa"

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/bastione-infetti#35]
colpa mia che non so usare bootstrap

**Comment by GabrieleMessina** [comment]
@cristianolongo  dove volevi posizionarlo?

**Comment by cristianolongo** [comment]
Dove è ora

Il 14/set/2016 21:18, "GabrieleMessina" notifications@github.com ha
scritto:

**Comment by fedefra** [comment]
an extra wrong div when echo the panel, now delete.
