### ISSUE TITLE
Inserire Mappa del Bastione in Home

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/bastione-infetti#5]
Iserire nella Home Page la mappa del Bastione

http://www.openstreetmap.org/way/42035803

**Comment by GabrieleMessina** [comment]
Ho appena aggiunto la mappa in home page

**Comment by cristianolongo** [comment]
Non sarebbe stato meglio inserire questa?

http://www.openstreetmap.org/way/42035803

**Comment by GabrieleMessina** [comment]
È quella solo che una volta inserita nel iframe non si vede la zona evidenziata

**Comment by cristianolongo** [comment]
ottimo grazie
